Update requirements.txt kombu 5.2.2
```
-----> Building on the Heroku-24 stack
-----> Determining which buildpack to use for this app
-----> Python app detected
-----> Using Python 3.9.13 specified in runtime.txt
 !     Warning: The runtime.txt file is deprecated.
 !     
 !     The runtime.txt file is deprecated since it has been replaced
 !     by the more widely supported .python-version file:
 !     https://devcenter.heroku.com/changelog-items/3141
 !     
 !     Please delete your runtime.txt file and create a new file named:
 !     .python-version
 !     
 !     Make sure to include the '.' at the start of the filename.
 !     
 !     In the new file, specify your app's Python version without
 !     quotes or a 'python-' prefix. For example:
 !     3.9
 !     
 !     We strongly recommend that you use the major version form
 !     instead of pinning to an exact version, since it will allow
 !     your app to receive Python security updates.
 !     
 !     In the future support for runtime.txt will be removed and
 !     this warning will be made an error.
 !     Warning: Support for Python 3.9 is ending soon!
 !     
 !     Python 3.9 will reach its upstream end-of-life in October 2025,
 !     at which point it will no longer receive security updates:
 !     https://devguide.python.org/versions/#supported-versions
 !     
 !     As such, support for Python 3.9 will be removed from this
 !     buildpack on 7th January 2026.
 !     
 !     Upgrade to a newer Python version as soon as possible, by
 !     changing the version in your runtime.txt file.
 !     
 !     For more information, see:
 !     https://devcenter.heroku.com/articles/python-support#supported-python-versions
 !     Warning: A Python patch update is available!
 !     
 !     Your app is using Python 3.9.13, however, there is a newer
 !     patch release of Python 3.9 available: 3.9.22
 !     
 !     It is important to always use the latest patch version of
 !     Python to keep your app secure.
 !     
 !     Update your runtime.txt file to use the new version.
 !     
 !     We strongly recommend that you do not pin your app to an
 !     exact Python version such as 3.9.13, and instead only specify
 !     the major Python version of 3.9 in your runtime.txt file.
 !     This will allow your app to receive the latest available Python
 !     patch version automatically and prevent this warning.
-----> Installing Python 3.9.13
-----> Installing pip 25.0.1, setuptools 70.3.0 and wheel 0.45.1
-----> Installing SQLite3
-----> Installing dependencies using 'pip install -r requirements.txt'
       Collecting amqp==5.0.6 (from -r requirements.txt (line 1))
         Downloading amqp-5.0.6-py3-none-any.whl.metadata (8.8 kB)
       Collecting billiard==3.6.4.0 (from -r requirements.txt (line 2))
         Downloading billiard-3.6.4.0-py3-none-any.whl.metadata (4.5 kB)
       Collecting cached-property==1.5.2 (from -r requirements.txt (line 3))
         Downloading cached_property-1.5.2-py2.py3-none-any.whl.metadata (11 kB)
       Collecting celery==5.2.1 (from -r requirements.txt (line 4))
         Downloading celery-5.2.1-py3-none-any.whl.metadata (20 kB)
       Collecting certifi==2021.5.30 (from -r requirements.txt (line 5))
         Downloading certifi-2021.5.30-py2.py3-none-any.whl.metadata (3.0 kB)
       Collecting chardet==4.0.0 (from -r requirements.txt (line 6))
         Downloading chardet-4.0.0-py2.py3-none-any.whl.metadata (3.5 kB)
       Collecting click==7.1.2 (from -r requirements.txt (line 7))
         Downloading click-7.1.2-py2.py3-none-any.whl.metadata (2.9 kB)
       Collecting click-didyoumean==0.0.3 (from -r requirements.txt (line 8))
         Downloading click-didyoumean-0.0.3.tar.gz (2.6 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting click-plugins==1.1.1 (from -r requirements.txt (line 9))
         Downloading click_plugins-1.1.1-py2.py3-none-any.whl.metadata (6.4 kB)
       Collecting click-repl==0.2.0 (from -r requirements.txt (line 10))
         Downloading click_repl-0.2.0-py3-none-any.whl.metadata (316 bytes)
       Collecting Flask==2.0.1 (from -r requirements.txt (line 11))
         Downloading Flask-2.0.1-py3-none-any.whl.metadata (3.8 kB)
       Collecting Flask-Assets==2.0 (from -r requirements.txt (line 12))
         Downloading Flask_Assets-2.0-py3-none-any.whl.metadata (961 bytes)
       Collecting Flask-SQLAlchemy==2.5.1 (from -r requirements.txt (line 13))
         Downloading Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl.metadata (3.1 kB)
       Collecting greenlet==1.1.0 (from -r requirements.txt (line 14))
         Downloading greenlet-1.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
       Collecting gunicorn==20.1.0 (from -r requirements.txt (line 15))
         Downloading gunicorn-20.1.0-py3-none-any.whl.metadata (3.8 kB)
       Collecting humanize==3.9.0 (from -r requirements.txt (line 16))
         Downloading humanize-3.9.0-py3-none-any.whl.metadata (7.5 kB)
       Collecting idna==2.10 (from -r requirements.txt (line 17))
         Downloading idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
       Collecting importlib-metadata==4.6.0 (from -r requirements.txt (line 18))
         Downloading importlib_metadata-4.6.0-py3-none-any.whl.metadata (4.1 kB)
       Collecting itsdangerous==2.0.1 (from -r requirements.txt (line 19))
         Downloading itsdangerous-2.0.1-py3-none-any.whl.metadata (2.9 kB)
       Collecting Jinja2==3.0.1 (from -r requirements.txt (line 20))
         Downloading Jinja2-3.0.1-py3-none-any.whl.metadata (3.5 kB)
       Collecting kombu==5.1.0 (from -r requirements.txt (line 21))
         Downloading kombu-5.1.0-py3-none-any.whl.metadata (2.6 kB)
       Collecting Markdown==3.3.4 (from -r requirements.txt (line 22))
         Downloading Markdown-3.3.4-py3-none-any.whl.metadata (4.6 kB)
       Collecting MarkupSafe==2.0.1 (from -r requirements.txt (line 23))
         Downloading MarkupSafe-2.0.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (3.2 kB)
       Collecting numpy==1.21.0 (from -r requirements.txt (line 24))
         Downloading numpy-1.21.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (2.0 kB)
       Collecting prompt-toolkit==3.0.19 (from -r requirements.txt (line 25))
         Downloading prompt_toolkit-3.0.19-py3-none-any.whl.metadata (7.0 kB)
       Collecting psycopg2==2.9.1 (from -r requirements.txt (line 26))
         Downloading psycopg2-2.9.1.tar.gz (379 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting pyScss==1.3.7 (from -r requirements.txt (line 27))
         Downloading pyScss-1.3.7.tar.gz (121 kB)
         Preparing metadata (setup.py): started
         Preparing metadata (setup.py): finished with status 'done'
       Collecting pytz==2021.1 (from -r requirements.txt (line 28))
         Downloading pytz-2021.1-py2.py3-none-any.whl.metadata (21 kB)
       Collecting PyYAML==5.4.1 (from -r requirements.txt (line 29))
         Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl.metadata (2.1 kB)
       Collecting redis==3.5.3 (from -r requirements.txt (line 30))
         Downloading redis-3.5.3-py2.py3-none-any.whl.metadata (36 kB)
       Collecting requests==2.25.1 (from -r requirements.txt (line 31))
         Downloading requests-2.25.1-py2.py3-none-any.whl.metadata (4.2 kB)
       Collecting scipy==1.7.0 (from -r requirements.txt (line 32))
         Downloading scipy-1.7.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (2.2 kB)
       Collecting six==1.16.0 (from -r requirements.txt (line 33))
         Downloading six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
       Collecting SQLAlchemy==1.4.20 (from -r requirements.txt (line 34))
         Downloading SQLAlchemy-1.4.20-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.4 kB)
       Collecting typing-extensions==3.10.0.0 (from -r requirements.txt (line 35))
         Downloading typing_extensions-3.10.0.0-py3-none-any.whl.metadata (2.1 kB)
       Collecting urllib3==1.26.6 (from -r requirements.txt (line 36))
         Downloading urllib3-1.26.6-py2.py3-none-any.whl.metadata (44 kB)
       Collecting vine==5.0.0 (from -r requirements.txt (line 37))
         Downloading vine-5.0.0-py2.py3-none-any.whl.metadata (2.2 kB)
       Collecting wcwidth==0.2.5 (from -r requirements.txt (line 38))
         Downloading wcwidth-0.2.5-py2.py3-none-any.whl.metadata (11 kB)
       Collecting webassets==2.0 (from -r requirements.txt (line 39))
         Downloading webassets-2.0-py3-none-any.whl.metadata (889 bytes)
       Collecting Werkzeug==2.0.1 (from -r requirements.txt (line 40))
         Downloading Werkzeug-2.0.1-py3-none-any.whl.metadata (4.4 kB)
       Collecting xlrd==2.0.1 (from -r requirements.txt (line 41))
         Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
       Collecting zipp==3.5.0 (from -r requirements.txt (line 42))
         Downloading zipp-3.5.0-py3-none-any.whl.metadata (2.3 kB)
       INFO: pip is looking at multiple versions of celery to determine which version is compatible with other requirements. This could take a while.
       ERROR: Cannot install -r requirements.txt (line 4) and kombu==5.1.0 because these package versions have conflicting dependencies.
       
       The conflict is caused by:
           The user requested kombu==5.1.0
           celery 5.2.1 depends on kombu<6.0 and >=5.2.2
       
       To fix this you could try to:
       1. loosen the range of package versions you've specified
       2. remove package versions to allow pip to attempt to solve the dependency conflict
       
       ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
 !     Error: Unable to install dependencies using pip.
 !     
 !     See the log output above for more information.
 !     Push rejected, failed to compile Python app.
 !     Push failed
```